"use-strict";
//@ts-check

const {BinanceScraper} = require("../../Binance_Scraper")
const {MongoDatabase} = require("../../MongoDatabase")
/**
 * 
 * @param {{binance:BinanceScraper,mongoDatabase:MongoDatabase}} param0 
 * @param {import("../../Binance_Scraper/getLeaderboardRank_API").GetOtherLeaderboardBaseInfo_API_Payload_Interface}  getOtherPerformance_API_Payload_Interface
 */
module.exports.leaderboardTradersAndStatsHandler = async function leaderboardTradersAndStatsHandler({binance,mongoDatabase},getOtherPerformance_API_Payload_Interface){
    try{
        const binanceTradersAndTheirInfo = await binance.getTradersTheirInfoStatistics(binance.globalPage,getOtherPerformance_API_Payload_Interface)

        /**
         * 2. Loop through the traders and their info and save or edit the required;
         */
        for(const binanceTraderInfo of binanceTradersAndTheirInfo){
            const {performance:traderPerformance,trader} = binanceTraderInfo;
           

            //a. save trader to db if not already saved
            const savedTrader = await mongoDatabase.collection.topTradersCollection.getDocumentByTraderUid(trader.encryptedUid);
            console.log({savedTrader,username:trader.toJson()})

            if(!savedTrader){
                //trader in db not found
                // create in db
                mongoDatabase.collection.topTradersCollection.createNewDocument({
                    username: trader.nickName,
                    uid: trader.encryptedUid,
                    copied: false,
                    followed: false,
                    updatedOn:Date.now(),
                    allPNL: 
                        binance.
                            utils.
                                traderPerformance.
                                    getValueForPerformance(
                                        traderPerformance,
                                        {
                                            periodType:"ALL",
                                            statisticsType:"PNL"
                                        }
                                    ),
                    allROI: 
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"ALL",
                                        statisticsType:"ROI"
                                    }
                                ),
                    dailyPNL: 
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"DAILY",
                                        statisticsType:"PNL"
                                    }
                                ),
                    dailyROI: 
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"DAILY",
                                        statisticsType:"ROI"
                                    }
                                ),
                    weeklyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"WEEKLY",
                                        statisticsType:"PNL"
                                    }
                                ),
                    weeklyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"WEEKLY",
                                        statisticsType:"ROI"
                                    }
                                ),
                    monthlyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"MONTHLY",
                                        statisticsType:"PNL"
                                    }
                                ),
                    monthlyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"MONTHLY",
                                        statisticsType:"ROI"
                                    }
                                ),
                    yearlyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"YEARLY",
                                        statisticsType:"PNL"
                                    }
                                ),
                    yearlyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"YEARLY",
                                        statisticsType:"ROI"
                                    }
                                ),
                    // exacts
                    exactWeeklyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_WEEKLY",
                                        statisticsType:"PNL"
                                    }
                                ),
                    exactWeeklyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_WEEKLY",
                                        statisticsType:"ROI"
                                    }
                                ),
                    exactMonthlyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_MONTHLY",
                                        statisticsType:"PNL"
                                    }
                                ),
                    exactMonthlyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_MONTHLY",
                                        statisticsType:"ROI"
                                    }
                                ),
                    exactYearlyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_YEARLY",
                                        statisticsType:"PNL"
                                    }
                                ),
                    exactYearlyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_YEARLY",
                                        statisticsType:"ROI"
                                    }
                                ),
                    
                })
            }else {
                // trader is available // needs update
                await mongoDatabase.collection.topTradersCollection.updateDocument(savedTrader._id,{
                    username: trader.nickName,
                    uid: trader.encryptedUid,
                    copied: savedTrader.copied,
                    followed: savedTrader.followed,
                    updatedOn:Date.now(),
                    allPNL: 
                        binance.
                            utils.
                                traderPerformance.
                                    getValueForPerformance(
                                        traderPerformance,
                                        {
                                            periodType:"ALL",
                                            statisticsType:"PNL"
                                        },
                                        savedTrader.allPNL
                                    ),
                    allROI: 
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"ALL",
                                        statisticsType:"ROI"
                                    },
                                    savedTrader.allROI
                                ),
                    dailyPNL: 
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"DAILY",
                                        statisticsType:"PNL"
                                    },
                                    savedTrader.dailyPNL
                                ),
                    dailyROI: 
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"DAILY",
                                        statisticsType:"ROI"
                                    },
                                    savedTrader.dailyROI
                                ),
                    weeklyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"WEEKLY",
                                        statisticsType:"PNL"
                                    },
                                    savedTrader.weeklyPNL
                                ),
                    weeklyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"WEEKLY",
                                        statisticsType:"ROI"
                                    },
                                    savedTrader.weeklyROI
                                ),
                    monthlyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"MONTHLY",
                                        statisticsType:"PNL"
                                    },
                                    savedTrader.monthlyPNL
                                ),
                    monthlyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"MONTHLY",
                                        statisticsType:"ROI"
                                    },
                                    savedTrader.monthlyROI
                                ),
                    yearlyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"YEARLY",
                                        statisticsType:"PNL"
                                    },
                                    savedTrader.yearlyPNL
                                ),
                    yearlyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"YEARLY",
                                        statisticsType:"ROI"
                                    },
                                    savedTrader.yearlyROI
                                ),
                    // exacts
                    exactWeeklyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_WEEKLY",
                                        statisticsType:"PNL"
                                    },
                                    savedTrader.exactWeeklyPNL
                                ),
                    exactWeeklyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_WEEKLY",
                                        statisticsType:"ROI"
                                    },
                                    savedTrader.exactWeeklyROI
                                ),
                    exactMonthlyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_MONTHLY",
                                        statisticsType:"PNL"
                                    },
                                    savedTrader.exactMonthlyPNL
                                ),
                    exactMonthlyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_MONTHLY",
                                        statisticsType:"ROI"
                                    },
                                    savedTrader.exactMonthlyROI
                                ),
                    exactYearlyPNL:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_YEARLY",
                                        statisticsType:"PNL"
                                    },
                                    savedTrader.exactYearlyPNL
                                ),
                    exactYearlyROI:
                        binance.
                        utils.
                            traderPerformance.
                                getValueForPerformance(
                                    traderPerformance,
                                    {
                                        periodType:"EXACT_YEARLY",
                                        statisticsType:"ROI"
                                    },
                                    savedTrader.exactYearlyROI
                                ),
                })
            }
            // :: At this area a doc has been inserted
            
            

        }
        return;
    }catch(error){
        throw error;
    }
}